name: Deploy ECS App

on:
  workflow_dispatch:  # Manual trigger from GitHub Actions tab

jobs:
  deploy:
    name: Build & Deploy Docker App to ECS
    runs-on: ubuntu-latest

    steps:
    - name: â¬‡ï¸ Checkout Code
      uses: actions/checkout@v3

    - name: ğŸ›  Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: ğŸ§± Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0

    - name: ğŸ“¦ Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: ğŸ“‹ Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    - name: ğŸ“¤ Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform
    - name: ğŸ” Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image to ECR
      env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ecs-app-repo  # Match Terraform name
          IMAGE_TAG: latest
      run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
